## 1. CSV Files

CSV (Comma-Separated Values) is a common format for storing tabular data.
Pandas provides `read_csv()` to read CSV files and `to_csv()` to save DataFrames.

### Example

A company stores customer sales data in a CSV file.
We can load the file into Pandas for analysis.

In [1]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Tony", "John", "David"],
    "Sales": [5000, 7000, 4500]
})

df.to_csv("sales.csv", index=False)

data = pd.read_csv("sales.csv")

data

    Name  Sales
0   Tony   5000
1   John   7000
2  David   4500

### Output Explanation

The DataFrame is first saved as a CSV file and then loaded back into Pandas.
CSV is commonly used for sharing and storing structured datasets.

## 2. Excel Files

Pandas can read and write Excel files using `read_excel()` and `to_excel()`.
Excel files are commonly used in business reporting and data analysis.

### Example

A company maintains employee salary information in an Excel file.
Pandas can load this information for analysis.

In [2]:
import pandas as pd

df = pd.DataFrame({
    "Employee": ["Tony", "John", "David"],
    "Salary": [40000, 35000, 30000]
})

df.to_excel("employees.xlsx", index=False)

data = pd.read_excel("employees.xlsx")

data

  Employee  Salary
0     Tony   40000
1     John   35000
2    David   30000

### Output Explanation

The employee data is saved into an Excel file and then read back into a DataFrame.

## 3. JSON Files

JSON (JavaScript Object Notation) is a lightweight format used to store structured data.
Pandas provides `read_json()` and `to_json()` for JSON file operations.

### Example

An API may return customer information in JSON format.
Pandas can convert this data into a DataFrame for analysis.

In [3]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Tony", "John", "David"],
    "Age": [24, 25, 23]
})

df.to_json("customers.json", orient="records")

data = pd.read_json("customers.json")

data

    Name  Age
0   Tony   24
1   John   25
2  David   23

### Output Explanation

The DataFrame is stored as JSON and loaded back into Pandas.
JSON is frequently used when working with APIs and web applications.

## 3. Parquet Files

Parquet is a columnar file format designed for efficient storage and processing of large datasets.
It is commonly used in data engineering and big data applications.

### Example

An AI/ML project may contain a large dataset.
Parquet can store the data efficiently and preserve column data types.

In [5]:
import pandas as pd

df = pd.DataFrame({
    "Product": ["Laptop", "Phone", "Tablet"],
    "Price": [50000, 30000, 20000]
})

df.to_parquet("products.parquet", index=False)

data = pd.read_parquet("products.parquet")

data

  Product  Price
0  Laptop  50000
1   Phone  30000
2  Tablet  20000

### Output Explanation

The DataFrame is stored in Parquet format and loaded back successfully.
Parquet is useful for efficient storage and faster data processing.

## 5. mPickle Files

Pickle is a Python format used to serialize and store Python objects.
Pandas can use `to_pickle()` and `read_pickle()` to save and load DataFrames.

### Example

A processed DataFrame can be saved as a Pickle file
and reused later without repeating the preprocessing steps.

In [7]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Tony", "John", "David"],
    "Score": [85, 90, 78]
})

df.to_pickle("data.pkl")

data = pd.read_pickle("data.pkl")

data

    Name  Score
0   Tony     85
1   John     90
2  David     78

### Output Explanation

The DataFrame is serialized into a Pickle file and loaded again.
Pickle is useful for storing Python-specific objects.

## 6. SQL Tables

Pandas can read data from SQL databases using `read_sql()`.
A DataFrame can also be written to a SQL table using `to_sql()`.

### Example

A company stores customer information in a MySQL database.
Pandas can retrieve the SQL table and convert it into a DataFrame.

In [8]:
import pandas as pd
import sqlite3

connection = sqlite3.connect("company.db")

df = pd.DataFrame({
    "Name": ["Tony", "John", "David"],
    "Salary": [40000, 35000, 30000]
})

df.to_sql("employees", connection, if_exists="replace", index=False)

data = pd.read_sql("SELECT * FROM employees", connection)

data

    Name  Salary
0   Tony   40000
1   John   35000
2  David   30000

### Output Explanation

The DataFrame is stored as a SQL table and then retrieved using an SQL query.
This demonstrates how Pandas can work with database data.

## 7. Multiple Files

Sometimes data is divided into multiple files, such as monthly sales files.
Pandas can read multiple files and combine them into a single DataFrame.

### Example

A company has separate sales files for January, February, and March.
These files can be combined for quarterly analysis.

In [9]:
import pandas as pd

jan = pd.DataFrame({
    "Month": ["January", "January"],
    "Sales": [5000, 6000]
})

feb = pd.DataFrame({
    "Month": ["February", "February"],
    "Sales": [7000, 5500]
})

mar = pd.DataFrame({
    "Month": ["March", "March"],
    "Sales": [8000, 6500]
})

all_sales = pd.concat([jan, feb, mar], ignore_index=True)

all_sales

      Month  Sales
0   January   5000
1   January   6000
2  February   7000
3  February   5500
4     March   8000
5     March   6500

### Output Explanation

The three monthly DataFrames are combined into one DataFrame.
This approach is useful when data is divided across multiple files or periods.

## 8. File Paths

A file path tells Python where a file is located.
Using correct file paths is important when reading and writing datasets.

### Example

A dataset may be stored inside a `data` folder.
We can specify the relative or absolute path when loading the file.

In [11]:
import pandas as pd
from pathlib import Path

file_path = Path("data") / "sales.csv"

print(file_path)

# df = pd.read_csv(file_path)

data\sales.csv

### Output Explanation

`Path` creates the file path in a platform-independent way.
The path can then be passed to Pandas functions such as `read_csv()`.