## 1. head()

The `head()` function displays the first few rows of a DataFrame.
By default, it displays the first 5 rows and helps us quickly inspect the dataset.

### Example

In an AI/ML project, after loading a dataset, we can use `head()`
to quickly check what the first few records look like.

In [1]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Tony", "John", "David", "Sam", "Alex", "Ravi"],
    "Age": [24, 25, 23, 26, 22, 27],
    "Score": [85, 90, 78, 88, 92, 80]
})

df.head()

    Name  Age  Score
0   Tony   24     85
1   John   25     90
2  David   23     78
3    Sam   26     88
4   Alex   22     92

### Output Explanation

The first 5 rows of the DataFrame are displayed.
We can also use `df.head(3)` to display the first 3 rows.

## 2. tail()

The `tail()` function displays the last few rows of a DataFrame.
By default, it displays the last 5 rows.

### Example

After processing a dataset, `tail()` can be used to check
the last records and verify that the data was loaded correctly.

In [2]:
df.tail()

    Name  Age  Score
1   John   25     90
2  David   23     78
3    Sam   26     88
4   Alex   22     92
5   Ravi   27     80

### Output Explanation

The last 5 rows of the DataFrame are displayed.
We can use `df.tail(3)` to display the last 3 rows.

## 3. sample()

The `sample()` function randomly selects rows from a DataFrame.
It is useful for checking random records instead of only the beginning or end.

### Example

When working with a large dataset, we can randomly inspect a few records
to understand whether the data contains different types of values.

In [3]:
df.sample(3, random_state=42)

   Name  Age  Score
0  Tony   24     85
1  John   25     90
5  Ravi   27     80

### Output Explanation

Three random rows are displayed.
`random_state=42` makes the random selection reproducible.

## 4. info()

The `info()` function provides a summary of a DataFrame.
It shows the number of rows, columns, data types, and non-null values.

### Example

Before preprocessing an ML dataset, `info()` helps identify
missing values and incorrect data types.

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    6 non-null      str
 1   Age     6 non-null      int64
 2   Score   6 non-null      int64
dtypes: int64(2), str(1)
memory usage: 300.0 bytes

### Output Explanation

The output shows the DataFrame structure, number of entries,
column names, non-null counts, and data types.

## 5. describe()

The `describe()` function generates descriptive statistics for numerical columns.
It provides count, mean, standard deviation, minimum, maximum, and percentiles.

### Example

In a sales dataset, `describe()` can help understand the distribution
of numerical features such as price, quantity, and sales.

In [5]:
df.describe()

             Age      Score
count   6.000000   6.000000
mean   24.500000  85.500000
std     1.870829   5.576737
min    22.000000  78.000000
25%    23.250000  81.250000
50%    24.500000  86.500000
75%    25.750000  89.500000
max    27.000000  92.000000

### Output Explanation

The output provides summary statistics for numerical columns.
These statistics help us understand the general behavior of the data.

## 6. shape

The `shape` attribute returns the number of rows and columns in a DataFrame.
The result is represented as `(rows, columns)`.

### Example

Before training an ML model, we can check the dataset size
to understand how many records and features are available.

In [6]:
df.shape

(6, 3)

### Output Explanation

The output shows the number of rows and columns.
For example, `(6, 3)` means 6 rows and 3 columns.

## 7. columns

The `columns` attribute returns the names of all columns in a DataFrame.
It helps us understand the features available in the dataset.

### Example

In an ML dataset, we can use `columns` to identify
which features are available before selecting them.

In [7]:
df.columns

Index(['Name', 'Age', 'Score'], dtype='str')

### Output Explanation

The output displays all column names in the DataFrame.

## 8. dtypes

The `dtypes` attribute shows the data type of each column.
It helps us understand how Pandas represents each feature.

### Example

Before preprocessing, we can check whether columns contain
integers, floating-point values, strings, or other data types.

In [8]:
df.dtypes

Name       str
Age      int64
Score    int64
dtype: object

### Output Explanation

The output shows the data type of each column.
Checking data types helps prevent errors during data processing.

## 9. memory_usage()

The `memory_usage()` function shows how much memory each column uses.
It is useful when working with large datasets.

### Example

An AI/ML dataset may contain millions of rows.
Checking memory usage helps us identify columns that consume too much memory.

In [9]:
df.memory_usage(deep=True)

Index    132
Name      72
Age       48
Score     48
dtype: int64

### Output Explanation

The output shows the memory used by each column in bytes.
`deep=True` provides a more accurate memory calculation for object/string data.

## 10. nunique()

The `nunique()` function returns the number of unique values in each column.
It is useful for understanding the variety of values in categorical features.

### Example

In customer data, we may want to know how many unique ages,
cities, or product categories are present.

In [10]:
df.nunique()

Name     6
Age      6
Score    6
dtype: int64

### Output Explanation

The output shows the number of unique values in each column.
This can help identify categorical features and high-cardinality columns.

## 11. value_counts()

The `value_counts()` function counts how frequently each unique value occurs.
It is mainly used for analyzing categorical columns.

### Example

A company can use `value_counts()` to find how many customers
belong to each city or product category.

In [11]:
customer_data = pd.DataFrame({
    "City": ["Chennai", "Madurai", "Chennai", "Trichy", "Chennai", "Madurai"]
})

customer_data["City"].value_counts()

City
Chennai    3
Madurai    2
Trichy     1
Name: count, dtype: int64

### Output Explanation

The output shows the frequency of each city.
For example, Chennai appears more frequently than the other cities.