## 1. loc

`loc` is used to select rows and columns using labels.
It is useful when we know the row index or column names.

### Example

Suppose we have employee data and want to select the employee
with a specific index or retrieve specific columns by their names.

In [1]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Tony", "John", "David"],
    "Age": [24, 25, 23],
    "Salary": [40000, 35000, 30000]
}, index=["E101", "E102", "E103"])

df.loc["E101"]

Name       Tony
Age          24
Salary    40000
Name: E101, dtype: object

### Output Explanation

`loc` selects the row using its label, which is `E101`.
We can also use `df.loc["E101", "Salary"]` to select one specific value.

## 2. iloc

`iloc` is used to select rows and columns using their integer positions.
The position starts from 0.

### Example

If we want to select the first row or first column based on position,
we can use `iloc`.

In [2]:
df.iloc[0]

Name       Tony
Age          24
Salary    40000
Name: E101, dtype: object

### Output Explanation

`iloc[0]` selects the first row because indexing starts from position 0.

## 3. Boolean Indexing

Boolean indexing filters data using conditions that return True or False.
It is commonly used to select records that satisfy a specific condition.

### Example

A company may want to identify employees whose salary is greater than 35000.

In [3]:
df[df["Salary"] > 35000]

      Name  Age  Salary
E101  Tony   24   40000

### Output Explanation

Only employees whose salary is greater than 35000 are displayed.

## 4. Filtering Rows

Filtering rows means selecting only the records that satisfy a condition.
It is useful for finding specific groups of data.

### Example

An HR department may want to find employees whose age is greater than 23.

In [4]:
df[df["Age"] > 23]

      Name  Age  Salary
E101  Tony   24   40000
E102  John   25   35000

### Output Explanation

The output contains only employees whose age is greater than 23.

## 5. query()

The `query()` function allows us to filter DataFrame rows using a string expression.
It can make complex filtering conditions easier to read.

### Example

We can use `query()` to find employees whose salary is greater than 35000.

In [5]:
df.query("Salary > 35000")

      Name  Age  Salary
E101  Tony   24   40000

### Output Explanation

The query returns employees whose salary is greater than 35000.

## 6. isin()

The `isin()` function checks whether values belong to a specified list of values.
It is useful when filtering for multiple categories.

### Example

A company may want to select employees whose names are Tony or David.

In [6]:
df[df["Name"].isin(["Tony", "David"])]

       Name  Age  Salary
E101   Tony   24   40000
E103  David   23   30000

### Output Explanation

Only rows where the Name is Tony or David are selected.

## 7. between()

The `between()` function checks whether values fall within a specified range.
By default, the boundary values are included.

### Example

An HR team may want to select employees whose salary is between 30000 and 40000.

In [7]:
df[df["Salary"].between(30000, 40000)]

       Name  Age  Salary
E101   Tony   24   40000
E102   John   25   35000
E103  David   23   30000

### Output Explanation

The output contains employees whose salary falls between 30000 and 40000.

## 8. Sorting

Sorting arranges DataFrame rows based on one or more columns.
Pandas provides `sort_values()` for sorting data.

### Example

A company may want to arrange employees from the highest salary
to the lowest salary.

In [8]:
df.sort_values(by="Salary", ascending=False)

       Name  Age  Salary
E101   Tony   24   40000
E102   John   25   35000
E103  David   23   30000

### Output Explanation

The employees are sorted from the highest salary to the lowest salary.
`ascending=False` sorts the values in descending order.