## 1. Rename Columns

The `rename()` function is used to change column names in a DataFrame.
Clear and meaningful column names make data easier to understand and work with.

### Example

A dataset may contain short column names such as `nm` and `sal`.
We can rename them to `Name` and `Salary` for better readability.

In [1]:
import pandas as pd

df = pd.DataFrame({
    "nm": ["Tony", "John", "David"],
    "sal": [40000, 35000, 30000]
})

df = df.rename(columns={
    "nm": "Name",
    "sal": "Salary"
})

df

    Name  Salary
0   Tony   40000
1   John   35000
2  David   30000

### Output Explanation

The column names `nm` and `sal` are changed to `Name` and `Salary`.

## 2. Drop Rows and Columns

The `drop()` function is used to remove unwanted rows or columns.
It is commonly used during data cleaning and preprocessing.

### Example

If a dataset contains an unnecessary column such as `Temporary_ID`,
we can remove it before analysis.

In [2]:
df = pd.DataFrame({
    "Name": ["Tony", "John", "David"],
    "Salary": [40000, 35000, 30000],
    "Temporary_ID": [101, 102, 103]
})

df = df.drop(columns=["Temporary_ID"])

df

    Name  Salary
0   Tony   40000
1   John   35000
2  David   30000

### Output Explanation

The `Temporary_ID` column is removed from the DataFrame.

## 3. Insert Columns

The `insert()` function adds a new column at a specific position.
It is useful when we want control over where the new column appears.

### Example

We can insert an `Age_Group` column between existing columns
based on the employee's age.

In [3]:
df = pd.DataFrame({
    "Name": ["Tony", "John", "David"],
    "Age": [24, 35, 23],
    "Salary": [40000, 35000, 30000]
})

df.insert(2, "Age_Group", ["Young", "Adult", "Young"])

df

    Name  Age Age_Group  Salary
0   Tony   24     Young   40000
1   John   35     Adult   35000
2  David   23     Young   30000

### Output Explanation

The `Age_Group` column is inserted at position 2.

## 4. assign()

The `assign()` function is used to create new columns or modify existing columns.
It returns a new DataFrame instead of directly changing the original DataFrame.

### Example

In a sales dataset, we can calculate total sales
by multiplying quantity and price.

In [4]:
df = pd.DataFrame({
    "Product": ["Laptop", "Phone", "Tablet"],
    "Quantity": [2, 3, 4],
    "Price": [50000, 30000, 20000]
})

new_df = df.assign(
    Total_Sales=df["Quantity"] * df["Price"]
)

new_df

  Product  Quantity  Price  Total_Sales
0  Laptop         2  50000       100000
1   Phone         3  30000        90000
2  Tablet         4  20000        80000

### Output Explanation

A new `Total_Sales` column is created using Quantity × Price.
The original DataFrame remains unchanged.

## 5. apply()

The `apply()` function applies a function to values in a Series or DataFrame.
It is useful when we need custom transformations.

### Example

We can classify employee salaries as High or Low
using a custom function.

In [5]:
df = pd.DataFrame({
    "Name": ["Tony", "John", "David"],
    "Salary": [40000, 35000, 30000]
})

def salary_category(salary):
    if salary >= 35000:
        return "High"
    else:
        return "Low"

df["Category"] = df["Salary"].apply(salary_category)

df

    Name  Salary Category
0   Tony   40000     High
1   John   35000     High
2  David   30000      Low

### Output Explanation

The custom function is applied to every value in the Salary column.
A new category is created based on the salary.

## 6. map()

The `map()` function is commonly used to transform values in a Pandas Series.
It is useful for replacing or mapping individual values to new values.

### Example

Suppose a dataset contains short department codes.
We can map those codes to full department names.

In [6]:
df = pd.DataFrame({
    "Employee": ["Tony", "John", "David"],
    "Department": ["AI", "HR", "AI"]
})

department_map = {
    "AI": "Artificial Intelligence",
    "HR": "Human Resources"
}

df["Department"] = df["Department"].map(department_map)

df

  Employee               Department
0     Tony  Artificial Intelligence
1     John          Human Resources
2    David  Artificial Intelligence

### Output Explanation

The short department codes are replaced with their full names.

## 7. replace()

The `replace()` function is used to replace specific values with other values.
It can be applied to individual columns or an entire DataFrame.

### Example

A dataset may contain inconsistent values such as `M` and `Male`.
We can replace `M` with `Male` to standardize the data.

In [7]:
df = pd.DataFrame({
    "Name": ["Tony", "John", "David"],
    "Gender": ["M", "Male", "M"]
})

df["Gender"] = df["Gender"].replace({
    "M": "Male"
})

df

    Name Gender
0   Tony   Male
1   John   Male
2  David   Male

### Output Explanation

All `M` values are replaced with `Male`.
This helps maintain consistency in the dataset.

## 8. Duplicate Handling

Duplicate records are repeated rows in a dataset.
Pandas provides `duplicated()` to identify duplicates and `drop_duplicates()` to remove them.

### Example

A customer dataset may accidentally contain the same customer record multiple times.
We can identify and remove duplicate records during data cleaning.

In [8]:
df = pd.DataFrame({
    "Name": ["Tony", "John", "Tony", "David"],
    "Age": [24, 25, 24, 23]
})

print("Duplicate Rows:")
print(df[df.duplicated()])

df = df.drop_duplicates()

print("\nAfter Removing Duplicates:")
print(df)

Duplicate Rows:
   Name  Age
2  Tony   24

After Removing Duplicates:
    Name  Age
0   Tony   24
1   John   25
3  David   23

### Output Explanation

`duplicated()` identifies repeated rows.
`drop_duplicates()` removes the duplicate records and keeps one copy.