## 1. groupby()

The `groupby()` function is used to divide data into groups based on one or more columns.
It is useful for analyzing data category-wise, such as sales by product or department.

### Example

A company wants to calculate sales separately for each product category.
We can group the sales data by the Product column.

In [2]:
import pandas as pd

df = pd.DataFrame({
    "Product": ["Laptop", "Phone", "Laptop", "Phone", "Tablet"],
    "Sales": [50000, 30000, 45000, 35000, 20000]
})

df.groupby("Product")["Sales"].sum()

Product
Laptop    95000
Phone     65000
Tablet    20000
Name: Sales, dtype: int64

### Output Explanation

The data is grouped by Product and the total sales for each product are calculated.

## 2. agg()

The `agg()` function is used to apply multiple aggregation functions to grouped data.
Common functions include sum, mean, minimum, maximum, and count.

### Example

A business may want to know the total, average, minimum, and maximum sales
for each product category.

In [3]:
df.groupby("Product")["Sales"].agg(["sum", "mean", "min", "max"])

           sum     mean    min    max
Product
Laptop   95000  47500.0  45000  50000
Phone    65000  32500.0  30000  35000
Tablet   20000  20000.0  20000  20000

### Output Explanation

The output provides multiple summary statistics for each product.
This gives a more complete view of the sales data.

## 3. transform()

The `transform()` function performs a calculation within each group
while keeping the original number of rows.
It is useful when we want group-level information for every individual record.

### Example

We can calculate the average sales for each product
and place that average beside every corresponding sales record.

In [4]:
df["Product_Avg_Sales"] = (
    df.groupby("Product")["Sales"].transform("mean")
)

df

  Product  Sales  Product_Avg_Sales
0  Laptop  50000            47500.0
1   Phone  30000            32500.0
2  Laptop  45000            47500.0
3   Phone  35000            32500.0
4  Tablet  20000            20000.0

### Output Explanation

Each row now contains the average sales of its corresponding product.
Unlike `groupby().mean()`, `transform()` keeps the original number of rows.

## 4. filter()

The `filter()` function is used with grouped data to keep or remove entire groups
based on a condition.

### Example

Suppose a company wants to keep only products whose total sales
are greater than 70000.

In [5]:
filtered_df = df.groupby("Product").filter(
    lambda group: group["Sales"].sum() > 70000
)

filtered_df

  Product  Sales  Product_Avg_Sales
0  Laptop  50000            47500.0
2  Laptop  45000            47500.0

### Output Explanation

Only product groups whose total sales exceed 70000 are retained.
The filtering decision is made at the group level.

## 5. Pivot Tables

A pivot table summarizes data based on one or more categories.
Pandas provides `pivot_table()` to create flexible summaries of DataFrames.

### Example

A company wants to compare total sales for different products.
A pivot table can summarize the sales by product.

In [6]:
pivot = pd.pivot_table(
    df,
    values="Sales",
    index="Product",
    aggfunc="sum"
)

pivot

         Sales
Product
Laptop   95000
Phone    65000
Tablet   20000

### Output Explanation

The pivot table shows the total sales for each product.
Pivot tables are useful for business reports and data analysis.

## 6. Crosstab

A crosstab creates a frequency table showing the relationship between
two or more categorical variables.
Pandas provides `pd.crosstab()` for this purpose.

### Example

A company may want to know how many customers belong to each combination
of gender and product category.

In [7]:
customers = pd.DataFrame({
    "Gender": ["Male", "Female", "Male", "Female", "Male"],
    "Product": ["Laptop", "Phone", "Phone", "Laptop", "Tablet"]
})

pd.crosstab(
    customers["Gender"],
    customers["Product"]
)

Product  Laptop  Phone  Tablet
Gender
Female        1      1       0
Male          1      1       1

### Output Explanation

The crosstab shows the number of records for each Gender-Product combination.
It is useful for analyzing relationships between categorical variables.