## 1. concat()

The `concat()` function combines two or more Pandas objects along rows or columns.
It is useful when datasets have similar structures and need to be combined.

### Example

A company stores January and February sales in separate DataFrames.
We can combine them into one DataFrame using `concat()`.

In [1]:
import pandas as pd

jan_sales = pd.DataFrame({
    "Product": ["Laptop", "Phone"],
    "Sales": [50000, 30000]
})

feb_sales = pd.DataFrame({
    "Product": ["Tablet", "Phone"],
    "Sales": [20000, 35000]
})

combined_sales = pd.concat(
    [jan_sales, feb_sales],
    ignore_index=True
)

combined_sales

  Product  Sales
0  Laptop  50000
1   Phone  30000
2  Tablet  20000
3   Phone  35000

### Output Explanation

The January and February DataFrames are combined row by row.
`ignore_index=True` creates a new continuous index.

## 2. merge()

The `merge()` function combines DataFrames using one or more common columns.
It works similarly to SQL joins.

### Example

A company has separate customer and order datasets.
Both datasets contain `Customer_ID`, which can be used to combine them.

In [2]:
customers = pd.DataFrame({
    "Customer_ID": [101, 102, 103],
    "Name": ["Tony", "John", "David"]
})

orders = pd.DataFrame({
    "Customer_ID": [101, 102, 103],
    "Amount": [500, 700, 450]
})

merged_data = pd.merge(
    customers,
    orders,
    on="Customer_ID",
    how="inner"
)

merged_data

   Customer_ID   Name  Amount
0          101   Tony     500
1          102   John     700
2          103  David     450

### Output Explanation

The two DataFrames are combined using `Customer_ID`.
The `inner` merge returns records that have matching Customer IDs in both DataFrames.

## 3. join()

The `join()` function combines DataFrames using their indexes by default.
It is useful when related information is stored using the same index.

### Example

An employee DataFrame contains names, while another DataFrame
contains their salaries using the same employee IDs as the index.

In [3]:
employees = pd.DataFrame({
    "Name": ["Tony", "John", "David"]
}, index=[101, 102, 103])

salary = pd.DataFrame({
    "Salary": [40000, 35000, 30000]
}, index=[101, 102, 103])

result = employees.join(salary)

result

      Name  Salary
101   Tony   40000
102   John   35000
103  David   30000

### Output Explanation

The two DataFrames are joined using their indexes.
The employee names and salaries are combined into one DataFrame.

## 4. append() and Alternatives

The old DataFrame `append()` method was deprecated and removed from modern Pandas.
The recommended alternative for adding rows is `pd.concat()`.

### Example

Previously, `append()` could be used to add one DataFrame to another.
Today, `pd.concat()` should be used instead.

In [4]:
df1 = pd.DataFrame({
    "Name": ["Tony"],
    "Score": [85]
})

df2 = pd.DataFrame({
    "Name": ["John"],
    "Score": [90]
})

result = pd.concat(
    [df1, df2],
    ignore_index=True
)

result

   Name  Score
0  Tony     85
1  John     90

### Output Explanation

The two DataFrames are combined using `pd.concat()`.
This is the modern replacement for the deprecated `append()` method.

## 5. combine_first()

The `combine_first()` function fills missing values in one DataFrame
using corresponding values from another DataFrame.

### Example

Suppose one customer dataset contains some missing information,
while another dataset has those missing values available.
We can use `combine_first()` to fill the gaps.

In [5]:
df1 = pd.DataFrame({
    "Name": ["Tony", "John", "David"],
    "City": ["Chennai", None, "Trichy"]
}, index=[101, 102, 103])

df2 = pd.DataFrame({
    "Name": ["Tony", "John", "David"],
    "City": ["Chennai", "Madurai", "Trichy"]
}, index=[101, 102, 103])

result = df1.combine_first(df2)

result

      Name     City
101   Tony  Chennai
102   John  Madurai
103  David   Trichy

### Output Explanation

The missing city value for John is filled using the value from `df2`.
Existing non-missing values in `df1` are retained.